accept_eula: no

ingress:
  hostname: "<hostname>"
  tls: false

secrets:
  password: "<search_password>"
  pull_secret: ""  # name of secret for pulling docker nucleus images. Should be created before deploying helm chart
  tls_secret: "<tls_secret_name>"  # name of TLS secret
  nucleus_secret: "nucleus-secrets"  # name of nucleus secret

image:
  name: "nucleus-search"
  registry: "gitlab-master.nvidia.com:5005/omniverse/search-service"
  tag: "2.2.0_mr59.gitlab.3049479.1dcdf6c4"

#extra_env_vars:
#  - name: SERVICE_RETRY_TIMEOUT
#    value: 10.0
