{{- if .Values.storage.local.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nucleus-tagging
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: {{ .Values.storage.local.path }}/ov-nucleus-tagging-{{ .Release.Name }}
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.local.node }}
{{- end }}