apiVersion: v1
kind: Secret
metadata:
  name: nucleus-tagging-passwords
  namespace: {{ .Release.Namespace }}
data:
  {{ $ov_password := .Values.secrets.password }}
  {{ if $ov_password }}
  ov_password: {{ $ov_password | b64enc | quote }}
  {{ else }}
  ov_password: {{ randAlpha 9 | b64enc | quote }}
  {{ end }}