apiVersion: v1
kind: Service
metadata:
  name: nucleus-tagging
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3020
      targetPort: 3020
      protocol: TCP
      name: transport
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: metrics
  selector:
    app: nucleus-tagging