apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-web-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: nucleus-web-ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nucleus-web-ui
  template:
    metadata:
      labels:
        app: nucleus-web-ui
    spec:
      imagePullSecrets:
      - name: {{ include "local_or_global" (list "secrets.pull_secret" .) | trim }}
      containers:
      - name: nucleus-web-ui
          {{ with .Values.image }}
        image: "{{ .registry }}/{{ .name }}:{{ .tag }}{{ if .digest }}@{{ .digest }}{{ end }}"
          {{ end }}
        env:
          - name: ACCEPT_EULA
            value: {{ include "local_or_global" (list "accept_eula" .) | trim | quote }}
          - name: PUBLIC_URL
            value: {{ if eq (include "local_or_global" (list "ingress.tls" .) | trim) "true" }}https{{ else }}http{{ end }}://{{ include "local_or_global" (list "ingress.hostname" .) | trim }}/omni/web/
          - name: SERVICE_BACKEND_DISCOVERY_URL
            value: {{ if eq (include "local_or_global" (list "ingress.tls" .) | trim) "true" }}wss{{ else }}ws{{ end }}://{{ include "local_or_global" (list "ingress.hostname" .) | trim }}/omni/discovery
          - name: OV_DEFAULT_SERVER
            value: {{ include "local_or_global" (list "ingress.hostname" .) | trim }}
          - name: SERVICE_BACKEND_DEPLOYMENTS_LOOKUP
            value: "internal"
          {{- if .Values.extra_env_vars }}
          {{- range .Values.extra_env_vars }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          {{ end }}
