apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nucleus-lft
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  {{ if eq (include "local_or_global" (list "ingress.tls" .) | trim) "true" }}
  tls:
  - hosts:
      - {{ include "local_or_global" (list "ingress.hostname" .) | trim }}
    secretName: {{ include "local_or_global" (list "secrets.tls_secret" .) | trim }}
  {{ end }}
  rules:
  - host: {{ include "local_or_global" (list "ingress.hostname" .) | trim }}
    http:
      paths:
      - path: /omni/lft(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: nucleus-lft
            port:
              number: 3030