apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nucleus
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - {{ .Values.storage.access_mode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}