apiVersion: v1
kind: Secret
metadata:
  name: nucleus-master-password
  namespace: {{ .Release.Namespace }}
data:
  {{ $master_password := include "local_or_global" (list "secrets.master_password" .) | trim }}
  {{ if $master_password }}
  master_password: {{ $master_password | b64enc | quote }}
  {{ else }}
  master_password: {{ randAlpha 9 | b64enc | quote }}
  {{ end }}
