apiVersion: v1
kind: Service
metadata:
  name: nucleus-resolver-cache
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8891
      targetPort: 8891
      protocol: TCP
      name: http
    - port: 9500
      targetPort: 9500
      protocol: TCP
      name: metrics
  selector:
    app: nucleus-resolver-cache