apiVersion: v1
kind: Service
metadata:
  name: nucleus-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3009
      targetPort: 3009
      protocol: TCP
      name: http
    - port: 3019
      targetPort: 3019
      protocol: TCP
      name: https
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: backup-api
    - port: 3007
      targetPort: 3007
      protocol: TCP
      name: lft-interface
    - port: 3010
      targetPort: 3010
      protocol: TCP
      name: launcher-metrics
    - port: 9500
      targetPort: 9500
      protocol: TCP
      name: metrics
  selector:
    app: nucleus-api