apiVersion: v1
kind: Service
metadata:
  name: redis-messagebus
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: data
    - port: 9121
      targetPort: 9121
      protocol: TCP
      name: metrics
  selector:
    app: redis-messagebus