apiVersion: v1
kind: Service
metadata:
  name: nucleus-lft
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
      name: http
  selector:
    app: nucleus-lft