apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nucleus-thumbnails
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}