apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-search
  namespace: {{ .Release.Namespace }}
  labels:
    app: nucleus-search
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nucleus-search
  template:
    metadata:
      labels:
        app: nucleus-search
    spec:
      imagePullSecrets:
      - name: {{ include "local_or_global" (list "secrets.pull_secret" .) | trim }}
      containers:
      - name: nucleus-search
          {{ with .Values.image }}
        image: "{{ .registry }}/{{ .name }}:{{ .tag }}{{ if .digest }}@{{ .digest }}{{ end }}"
          {{ end }}
        env:
          - name: ACCEPT_EULA
            value: {{ include "local_or_global" (list "accept_eula" .) | trim | quote }}
          - name: SERVICE_BACKEND_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ov_password
                name: nucleus-search-passwords
          - name: SERVICE_DEPLOYMENTS
            valueFrom:
              configMapKeyRef:
                name: nucleus-search-configs
                key: service_deployments
          - name: OV_HOST_NAME
            value: {{ include "local_or_global" (list "ingress.hostname" .) | trim }}
          - name: SERVICE_HOST
            value: 0.0.0.0
          - name: SERVICE_DEPLOYMENTS_LOOKUP
            value: internal
          - name: SERVICE_DISCOVERY_TOKEN
            value: /omni/secrets/DISCOVERY_TOKEN
          - name: SERVICE_DISCOVERY_URL
            value: {{ if eq (include "local_or_global" (list "ingress.tls" .) | trim) "true" }}wss{{ else }}ws{{ end }}://{{ include "local_or_global" (list "ingress.hostname" .) | trim }}/omni/discovery
          {{- if .Values.extra_env_vars }}
          {{- range .Values.extra_env_vars }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          {{ end }}
        volumeMounts:
        - mountPath: /omni/secrets
          name: secrets
      volumes:
      - name: secrets
        secret:
          secretName: nucleus-secrets
          defaultMode: 0400
