apiVersion: v1
kind: Service
metadata:
  name: nucleus-search
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3400
      targetPort: 3400
      protocol: TCP
      name: transport
  selector:
    app: nucleus-search