apiVersion: v1
kind: Service
metadata:
  name: nucleus-discovery
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3333
      targetPort: 3333
      protocol: TCP
      name: discovery
  selector:
    app: nucleus-discovery