apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app: nucleus-auth
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nucleus-auth
  template:
    metadata:
      labels:
        app: nucleus-auth
    spec:
      imagePullSecrets:
      - name: {{ include "local_or_global" (list "secrets.pull_secret" .) | trim }}
      containers:
      - name: nucleus-auth
          {{ with .Values.image }}
        image: "{{ .registry }}/{{ .name }}:{{ .tag }}{{ if .digest }}@{{ .digest }}{{ end }}"
          {{ end }}
        env:
          - name: ACCEPT_EULA
            value: {{ include "local_or_global" (list "accept_eula" .) | trim | quote }}
          - name: MASTER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: master_password
                name: nucleus-auth-passwords
          - name: CREDENTIAL_USERS
            valueFrom:
              secretKeyRef:
                key: CREDENTIAL_USERS
                name: nucleus-auth-passwords
          - name: SERVICE_DEPLOYMENTS
            valueFrom:
              configMapKeyRef:
                name: nucleus-auth-configs
                key: service_deployments
          - name: PUBLIC_URL
            value: https://{{ include "local_or_global" (list "ingress.hostname" .) | trim }}/omni/auth/login/
          - name: SERVICE_PRIVATE_KEY
            value: /omni/secrets/JWT_PRIV_KEY
          - name: SERVICE_PUBLIC_KEY
            value: /omni/secrets/JWT_PUB_KEY
          - name: SERVICE_SALT
            value: /omni/secrets/SERVICE_SALT
          - name: SERVICE_DISCOVERY_TOKEN
            value: /omni/secrets/DISCOVERY_TOKEN
          - name: NVIDIA_SSO_APP_ID
            value: /omni/secrets/NVIDIA_SSO_APP_ID
          - name: NVIDIA_SSO_SECRET_ID
            value: /omni/secrets/NVIDIA_SSO_SECRET_ID
          - name: SAML_SSO_METADATA_FILE
            value: /omni/secrets/SAML_SSO_METADATA_FILE
          - name: SERVICE_DISCOVERY_URL
            value: {{ if eq (include "local_or_global" (list "ingress.tls" .) | trim) "true" }}wss{{ else }}ws{{ end }}://{{ include "local_or_global" (list "ingress.hostname" .) | trim }}/omni/discovery
          {{- if .Values.extra_env_vars }}
          {{- range .Values.extra_env_vars }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          {{ end }}
        volumeMounts:
        - mountPath: /omni/data
          name: nucleus-auth
          subPath: data
        - mountPath: /omni/secrets
          name: secrets
      volumes:
      - name: nucleus-auth
        persistentVolumeClaim:
          claimName: nucleus-auth
      - name: secrets
        secret:
          secretName: nucleus-secrets
          defaultMode: 0400
